bitwarden/contributing-docs

docs/getting-started/tools/index.md
Minor correction to the tools documentation. Fixes a broken link.
=> Correct nvm link reference definition

docusaurus.config.js, package-lock.json, package.json, src/theme/SearchBar/DocSearch.js, src/theme/SearchBar/algolia.css, src/theme/SearchBar/index.js, src/theme/SearchBar/lunar-search.js, src/theme/SearchBar/styles.css, src/theme/SearchBar/templates.js, src/theme/SearchBar/utils.js
https://github.com/praveenn77/docusaurus-lunr-search
Adds a search bar to the documents.
=> Add lunr search

docs/getting-started/tools/index.md
Fixes a minor typo for the ADB command / tool.
=> Fix typo for Android's adb tool

docs/getting-started/server/advanced-setup.md, docs/getting-started/server/scim.md, docs/getting-started/server/tunnel.md
Adds the Advanced Setup, Scim and Tunnel documentation.
=> Add missing internal documentation

docs/architecture/captchas/index.md
Moved the captcha documentation from Confluence.
=> Added captcha documentation

docs/architecture/adr/0001-reactive-forms.md, docs/architecture/adr/0002-public-module-npm-packages.md, docs/architecture/adr/0007-manifest-v3-browser-memory-caching.md, docs/architecture/adr/0012-angular-filename-convention.md, docs/architecture/adr/0014-typescript-strict.md
These comments appear in the table of content and we should remove them.
=> Remove optional comments

docs/architecture/adr/0016-decryption-in-views.md
=> Encryption ADR

docs/getting-started/clients/desktop/index.mdx
Covers a WSL scenario described in https://github.com/bitwarden/clients/issues/3544
=> Add documentation on cross compiling rust

docs/getting-started/clients/mobile/android/index.md, docs/getting-started/clients/web-vault/index.mdx, docs/getting-started/enterprise/directory-connector/jumpcloud.md, docs/getting-started/enterprise/directory-connector/open-ldap.md, docs/getting-started/enterprise/key-connector.mdx, docs/getting-started/server/admin.md, docs/getting-started/server/database/mssql/index.md, docs/getting-started/server/events.md, docs/getting-started/server/guide.md, docs/getting-started/server/scim.md, docs/getting-started/server/secrets/index.md, docs/getting-started/server/self-hosted/index.md, docs/getting-started/server/user-secrets.md, docs/index.mdx
Swap tab view for docker container scripts to the global developer type toggle.
=> Use global developer type toggle

docs/architecture/adr/0017-feature-management.md, docs/architecture/adr/0018-feature-management.md
ADR on how we'll begin to use a feature management service provider.
=> ADR on feature management

docs/architecture/adr/0016-web-push-sunset-signalr.md, docs/architecture/adr/0019-adopt-web-push.md
ADR on how we'll migrate to use of Web Push and a new provider for mobile and server, all vs. SignalR.
=> ADR on adoption of Web Push

docs/contributing/index.md
Added links for Github discussion spaces on the server, clients and mobile repo.
=> Add new links for Github discussions

docs/architecture/adr/0004-refactor-state-service.md
Update ADR0004 - Should be OrganizationService
=> Update ADR0004 - Should be OrganizationService

docs/contributing/index.md
Moved to using Org level discussion  as PR proposals often overlap multiple repos.
=> Update Github discussions link

docs/architecture/event-logs/index.md
Added documentation of Event Logs.
=> Added event log documentation

LICENSE_CC.txt, LICENSE_GPL.txt, README.md
Our license files got flip-flopped, this PR corrects that.
=> Fix license files :flushed:

docs/contributing/featureflags.md
Documentation on how to utilize feature flags, scoped to a Bitwarden developer.
=> [PM-1014] Feature flag creation, usage, and maintenance

docs/architecture/adr/0018-feature-management.md, docs/contributing/featureflags.md
Feature management has been implemented so mark the ADR as complete.
=> Mark feature management ADR as complete

docs/getting-started/clients/web-vault/index.mdx
We should guide contributors towards setting up their own certificates to avoid browser warnings, and ensure WebAuthn works.
=> Add information about SSL certificates

docs/getting-started/tools/index.md
Removed a 1st-person verb
This makes the documentation more professional
=> [PM-1396] Update index.md

package-lock.json, package.json, src/contexts/devMode.tsx
Upgrade prettier, includes some format changes.
=> Bump prettier

docs/contributing/template-repository.md
Explains the contents of the new template repository and how to use it.
=> Template repository usage

docs/getting-started/clients/web-vault/index.mdx
=> Migrate from tabs to context tags

.github/renovate.json
Copies over the Renovate template and enables it for GitHub Actions and NPM.
=> Use Renovate template

docs/getting-started/clients/mobile/android/index.md, docs/getting-started/clients/web-vault/webauthn.mdx, docs/getting-started/server/advanced-setup.md, docs/getting-started/server/scim.md, docs/getting-started/server/self-hosted/index.md, docs/getting-started/server/sso/index.md
Fixing some out-of-date information and typos in the Getting Started documentation.
=> Fix typos and out-of-date instructions

docs/architecture/adr/0012-angular-filename-convention.md, docs/architecture/clients/presentation/angular.md
=> Tweak the naming to be what we actually do

docs/getting-started/clients/mobile/ios/index.mdx, docs/getting-started/server/sso/local.md, docs/getting-started/server/sso/okta.mdx
Clarify documentation for:
- initial SSO setup
- determining the correct Xcode version to use for Xamarin.iOS
=> Doc Clarifications

docs/contributing/database-migrations/edd.mdx
Adds process instructions to try and keep track of future migrations a little better.
=> Add jira ticket instructions to future migrations

docs/contributing/index.md
Updated links to Github discussions instead of forum
=> Link to GitHub Discussions

docs/architecture/adr/index.mdx, docs/contributing/pull-requests/branching.md, docs/contributing/pull-requests/code-review.md, docs/contributing/pull-requests/index.md
=> Rename pods to teams

docs/getting-started/server/self-hosted/index.md, docs/getting-started/server/sso/local.md
=> Fix tip and note using wrong callout syntax

docs/contributing/pull-requests/branching.md, docs/contributing/pull-requests/code-review.md, docs/contributing/pull-requests/index.md
General sprucing-up of the PR contributing section. Includes
* improved criteria for long lived branches
* updated reviewer guidelines due to code owners files
* improved code review tips and requirements
=> Update pull request docs

docs/contributing/pull-requests/branching.md, docs/contributing/pull-requests/index.md
Refining updates from #142.
- Missed example branch: updated to include a descriptive section
=> Update example branch name

docs/getting-started/server/admin.md, docs/getting-started/server/portal.md
Added documentation for Bitwarden Portal RBAC.  I also changed the name from Admin Portal to Bitwarden Portal to reflect current terminology.
=> Added RBAC documentation

custom-words.txt, docs/architecture/adr/0020-observability-with-opentelemetry.md
ADR on embracing OpenTelemetry. Relates to #156. Successor of #151.
=> ADR on observability

docs/contributing/feature-flags.md
Few minor improvements to feature flag documentation. Also includes new information about the capability to set local overrides in code.
Relates to https://github.com/bitwarden/server/pull/3243.
=> Feature flag documentation updates and mentions about new local override capabilities

docs/getting-started/enterprise/key-connector.mdx
Update KeyConnector docs setup for ARM based Macs (M1, M2)
=> Update KeyConnector docs for ARM Macs

.github/CODEOWNERS, .github/renovate.json, .prettierignore
- Update renovate config with our template.
- Assign autofill as default owner of dependencies.
=> Update renovate config

docusaurus.config.js
Update config to point to main instead of master
=> Update config to point to main instead of master

custom-words.txt, docs/getting-started/server/public-api.md
Add documentation around
* what the public api is
* general development guidelines
* how to test your changes using SwaggerUI
=> Add docs for Public API development

docs/contributing/feature-flags.md
Added instructions on feature flag removal.
=> Add instructions for feature flag removal

docs/contributing/database-migrations/edd.mdx
=> [PM-5940] Update edd.mdx

package-lock.json, package.json, tsconfig.json
Apply prettier formatting changes
=> Prettier formatting updates

docs/contributing/template-repository.md
Amends the documentation to show what we're doing with the new Renovate config repo and what it provides.
=> Renovate documentation updates, for template repository

custom-words.txt, docs/contributing/template-repository.md
Documents the new scanners seen in https://github.com/bitwarden/template/pull/67.
=> Scanning in template repository

docs/contributing/user-secrets.md
An alternative way to edit user secrets through the vs code UI.
=> Editing user secrets on vscode

docs/getting-started/server/guide.md
Update the recommended .NET SDK version from 6.0 → 8.0 for the server. 
The link already takes you to a download landing page with .NET 8.
=> Update recommended install to NET 8.0 SDK

docs/getting-started/server/database/mssql/index.md, docs/getting-started/server/guide.md
Update MSSQL information to match the changes made in https://github.com/bitwarden/server/pull/3850.
=> Update migrate.ps1 instructions to refer to Migrator Utility

docs/getting-started/mobile/android/index.md
#335 broke linting because Github workflows don't run automatically on community PRs. I thought I'd run it but obviously not.
Fix linting, also capitalize "Android" while I'm here.
=> Fix linting

docs/getting-started/clients/browser/biometric.mdx
Add a link to the docs you have to follow to do Mac App Store Development build to the callout telling you to do it.
=> Add MasDev Link

docs/getting-started/sdk/secrets-manager/integrations/kubernetes.mdx
…or sm-kubernetes
Matt Bishop requested changes to the structure of the sm-kubernetes repo.  This PR reflects those changes.  We should wait to merge until that change has been merged.
=> SM k8s repository structure update

docs/getting-started/tools/index.md
With https://github.com/bitwarden/clients/pull/8078 we have bumped Node from V18 to V20. This updates our docs for anyone starting out with their environment.
=> Update used Node and Npm version

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/scan.yml
Tunes up a few workflows in some minor ways and adds the scanning workflow so we can control processing.
=> Workflow tuning

docs/getting-started/clients/cli/index.md
Noticed invalid `npm` command referenced in CLI docs.
In https://github.com/bitwarden/clients/pull/9092, we adjusted the `npm` commands available for the CLI.  This adjusts the documentation to reflect the new commands.
team
- ❓ (`:question:`) …
=> Update CLI command to match current package.json

docs/getting-started/clients/desktop/index.mdx
This fix corrects build instructions for the native module for Linux builds. Building from the current instructions results in building the app instead of the module.
team …
=> [PM-11033] Correct Linux native module directory

docs/getting-started/tools/index.md
N/A
The .Net SDK dependency was missing from the tools page. Add it in.
=> Add .Net SDK link

docs/getting-started/server/portal.md
N/A
We replaced `gulp` with `webpack` for the server MVC projects.  This changes the documentation to reflect the new command required to build the stylesheets.
team …
=> Updated portal setup to use webpack command

docs/architecture/deep-dives/authorization.md
N/A
Fix incorrect link in Architecture > Deep-Dives > Authorization
team
issue and could potentially benefit from …
=> Fix incorrect link in Architecture > Deep-Dives > Authorization

docs/getting-started/business/directory-connector/open-ldap.md, docs/getting-started/server/sso/local.md
NA
Our documentation currently references `docker-compose`, which is compose v1 (deprecated). It has been replaced with `docker compose`: https://docs.docker.com/compose/releases/migrate/
team
- 🤔 …
=> Use newer docker compose command

docs/architecture/deep-dives/push-notifications/mobile.md, docs/architecture/mobile-clients/ios/push-notification-troubleshooting.md
https://bitwarden.atlassian.net/browse/PM-7515
This adds a page accessible to Bitwarden Developers providing some additional information for troubleshooting Push Notification problems on iOS should they happen.
This is a port (with some slight verbiage updates) from [a Confluence page](https://bitwarden.atlassian.net/wiki/spaces/MNAE/pages/883654662/iOS+Push+Notification+Troubleshooting+Tips).
- Updated any necessary documentation (Confluence, …
=> [PM-7515] Create document for iOS push notification tips

docs/architecture/adr/0023-integration-identifiers.md
Originated from bot management discussions amongst leadership.
ADR to enhance our server request pipeline with additional validations and registration of integrations.
team …
=> ADR for integration identification

docs/architecture/adr/0014-typescript-strict.md
Establish guidelines for required Angular inputs, that are guaranteed to be non-null, but are not necessarily initialized in a constructor.
team …
=> Add guideline for required angular component input

docs/contributing/dependencies/index.md
Ensure new dependencies in a shared repository is assigned an owner.
team
issue and could potentially benefit …
=> Add a sentence about new dependencies

docs/getting-started/server/sso/local.md, docs/getting-started/server/sso/okta.mdx
When going through the setup for SSO I found the information lacking and had to reach out to a dev with how to create an enterprise account.
team …
=> Added a missing prereq for setting up sso.

docs/getting-started/sdk/internal/index.md
Point people towards the README files in case they have troubles building the different packages. It's also way of introducing people to the different frameworks/crates used for deploying to different platforms (WASM and UniFFI)
team
- ❓ …
=> Add some SDK build and crate references

docs/architecture/sdk/dependencies.md
Add a section about how we want to rely on dependencies in the SDK.
team
issue and could potentially benefit from …
=> Add a section about dependencies in the SDK

docs/getting-started/business/splunk-app.md
Updates contributing docs for Splunk SIEM app integration. Currently following the steps will error, due to breaking changes in poetry:
- The poetry export plugin needs to be installed explicitly (does not ship with poetry anymore)
- Recommends to use python 3.9 as default, since 3.8 is EOL
- Poetry `shell` command no longer exists and is not required - `poetry env use` activates it automatically
- Use Splunk Enterprise 9.3 explicitly, since `splunk:latest` image tag resolves to 9.4, which is not supported yet.
- Remove the legacy `beta` app name - Requires https://github.com/bitwarden/splunk/pull/77 to be merged first.
- Protected …
=> Update contributing docs for packaging and using Splunk SIEM app.

docs/getting-started/clients/browser/index.md, docs/getting-started/server/guide.md, docs/getting-started/server/self-hosted/index.mdx, docs/getting-started/tools/index.md
Microsoft has announced the [retirement](https://techcommunity.microsoft.com/blog/azuresqlblog/azure-data-studio-retirement/4371009) of Azure Data Studio, as of February 28, 2025.
This PR replaces references to Azure Data Studio with their recommended replacement - the MSSQL VSCode extension - in the Tools section, and uses more generic terminology elsewhere so we don't have to update as many places if tools change in the future.
- Updated any necessary …
=> Replace references to Azure Data Studio

.github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-193
This repo has a more restrictive Prettier configuration so apply and adjust.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …
=> Lint scanner

docs/getting-started/server/events.md
[PM-17562](https://bitwarden.atlassian.net/browse/PM-17562)
This is a companion PR to [Add Azure Service Bus for Distributed Events](https://github.com/bitwarden/server/pull/5382) in the server repo. This updates the documentation for the Events page to match the newly implemented Azure Service Bus support. It also refactors some of the existing RabbitMQ section to reflect a [refactor PR](https://github.com/bitwarden/server/pull/5357) in the server repo merged earlier this week..
- Communicated to DevOps …
=> [PM-17562] Add Azure Service Bus for Distributed Events

docs/getting-started/clients/desktop/update.md
Added some notes to make update testing easier and mention the Linux route
team
issue and could potentially …
=> fix: added info to update testing doc

custom-words.txt, docs/contributing/code-style/swift.md
https://bitwarden.atlassian.net/browse/PM-16998
This attempts to codify some of the code style conventions in the iOS codebase, and provides a place for us to document further decisions about code style.
team
- …
=> [PM-16998] Provide code style for Swift

docs/architecture/sdk/index.md, docs/architecture/sdk/secrets-manager.md
The `bitwarden` crate doesn't exist in the `sdk-internal` repository.
team
issue and could potentially benefit …
=> Move `bitwarden` crate to sm docs

docs/getting-started/business/splunk-app.md
N/A
The Splunk instructions assume you're connecting to an environment with https properly configured, such as production or QA/USDEV, however this isn't stated anywhere.
This PR just adds a note about this so that devs don't waste their time trying to use their local dev instance. I'll update it with instructions for local dev once I've figured out the https issues.
Also fixes a nit: lack of full stops.
- Updated any necessary documentation …
=> Splunk: add warning regarding https issues

docs/contributing/code-style/rust.md
Softens the phrasing around pattern matching to make it more clear that `match` has many usages and we want the engineers to use alternatives where they provide a more readable and concise result.
team
- 🤔 …
=> Soften phrasing around pattern matching

docs/architecture/deep-dives/ssh/agent.md, docs/architecture/deep-dives/ssh/index.md
Follow-up to #426.
Was out when the SSH docs were reviewed and found a few things to improve.
team
issue and …
=> Copyediting of the SSH docs

docs/getting-started/business/splunk-app.md
N/A
Update the Splunk documentation to use the docker compose file added in https://github.com/bitwarden/splunk/pull/82.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
=> Splunk: use docker compose command

docs/getting-started/clients/desktop/mac/index.md
no jira ticket created, saw this stale reference while setting up desktop locally
Update our contributing docs to accurately name the BRE team and its relevant tag
team …
=> update devops to BRE

docs/getting-started/clients/web-vault/index.mdx
=> Update link to EnvironmentService

docs/contributing/dependencies/index.md
=> Update reference to renovate config to include json5 extension seen in clients

.github/workflows/scan.yml
Fix Prettier linting error preventing build success
=> [Bugfix] Prettier linting error

docs/getting-started/server/events.md
[PM-17562](https://bitwarden.atlassian.net/browse/PM-17562)
This PR updates the Event Logging section to reflect that changes present in [PR #5654](https://github.com/bitwarden/server/pull/5654) in the server repo. Specifically, it adds information about the new integration and configuration architecture that allows for Events to be sent to different integrations and the addition of Slack as an available integration.
- Updated any necessary …
=> [PM-17562] Update for new event integrations configurations

.github/workflows/scan.yml
[BRE-609](https://bitwarden.atlassian.net/browse/BRE-609)
update workflows to be compliant with pull_request_target workflow linter rule ahead of changing rule log level to error
team …
=> update pull request target workflow step

docs/getting-started/server/database/ef/index.mdx
N/A
Improve the clarity of the entity framework setup instructions. This addresses a few pitfalls I experienced while following the instructions on my local.
([Rendered](https://database-setup-refinement.contributing-docs.pages.dev/getting-started/server/database/ef/)) …
=> refine entity framework database setup with lessons learned

docs/getting-started/clients/browser/index.md
Added the specific `npm run build:watch:firefox` command as step 1 in the Firefox testing section.
team
issue and …
=> Updated build instructions for firefox

docs/architecture/adr/0024-csharp-nullable-reference-types.md, docs/contributing/code-style/csharp.md
https://bitwarden.slack.com/archives/C04LE162PHA/p1747976565585009
Adds an ADR proposing the adoption of nullable reference types throughout the entire `server` repo.
team …
=> Add ADR for nullable reference types

docs/getting-started/server/events.md
[PM-17562](https://bitwarden.atlassian.net/browse/PM-17562)
This is a companion to [PR #5924 in the server repo](https://github.com/bitwarden/server/pull/5924). These two PRs together aim to move the more technical documentation about the architecture and code-level specifics into a README in the server repo, while moving the section in this repo more in the direction of local setup and configuration. To that end, I've simplified the graphs for the two services slightly, removed some more architectural sections, and added more details on how to configure the RabbitMQ delay plugin.
- Protected functional changes with optionality (feature …
=> [PM-17562] Update event integration documentation

docs/getting-started/clients/desktop/index.mdx
https://bitwarden.atlassian.net/browse/PM-22847
If you are building for Windows on ARM you might need to run `node desktop_native/build.js cross-platform`. This PR adds this to the "cross compile" section.
This hopefully will save time for other devs in the future.
team
- 📝 (`:memo:`) or ℹ️ …
=> [PM-22847] Update Desktop Build Instructions for Windows on ARM

docs/architecture/adr/0024-csharp-nullable-reference-types.md
=> Change `Proposed` to `Accepted`

docs/architecture/sdk/index.md
Update SDK docs with changes done in the sdk-internal repo.
team
issue and could potentially benefit from …
=> Update SDK docs

docs/getting-started/server/sso/local.md
Add a troubleshooting tip for the local idp instructions after wasting some time on this myself.
team
issue and …
=> Add idp troubleshooting tip

docs/contributing/feature-flags.md
https://bitwarden.slack.com/archives/C04LE162PHA/p1755924061427299
Adds additional content around when and why to use feature flags at all.
team …
=> Document when and why to use feature flags

docs/contributing/code-style/csharp.md, docs/contributing/code-style/sql.md
https://bitwarden.atlassian.net/browse/PM-25182
Added some controller guidelines for the server to improve the OpenAPI schema and allow better code generation on the SDK. These guidelines allow us to ensure that `HTTP Route <-> Controller action` is a 1:1 mapping, which is needed to avoid collissions on the SDK.
This is part of a series of PRs on server applying these guidelines, the list is in this ticket: [PM-25182](https://bitwarden.atlassian.net/browse/PM-25182)
Rendered: https://ps-server-controller-naming.contributing-docs.pages.dev/contributing/code-style/csharp#controller-action-guidelines
- Protected functional changes with …
=> [PM-25182] Add controller naming guidelines for server

.github/CODEOWNERS
Follow-up with some documentation moves from Confluence.
AppSec should also review security documentation changes here.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
=> Use AppSec as additional reviewer with security documentation

docs/contributing/ai.md, docs/getting-started/tools/index.md
Confluence discussion on documentation patterns.
Lists Claude Code and a couple MCP servers as part of a "getting started" setup here.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …
=> List AI tools

docs/contributing/ai.md
Internal review.
Expands on the security considerations with MCP servers and fixes a copy / paste error.
team …
=> Enhance AI security considerations, fix errors
