- docs/getting-started/server/ef/index.md
Adds documentation on how to get setup using `Infrastructure.IntegrationTest` locally so we can link to it as a requirement when EF Query changes are made.
> Add Local `Infrastructure.IntegrationTest` Instructions

- docs/getting-started/server/guide.mdx
Add instructions on how to set up the `dotnet format` pre-commit hook for server. It's in our [README.md](https://github.com/bitwarden/server#dotnet-format) but not in these docs.
> Add server pre-commit hook instructions

- docs/getting-started/clients/desktop/mac/index.md
I noticed an info callout on the MAS desktop doc is using the old format causing weirdness. Switch to the correct syntax.
> Fix info callout in MAS dev page

- docs/getting-started/clients/browser/index.md
Streamline the Safari development steps, putting more focus on the Xcode approach since it's by far nicer to work with.
> Improve safari development documentation

- docs/getting-started/server/ef/index.md
For those less familiar with our migrations process, there was no clear documentation on how the migration scripts should be named (underscores vs. dashes, for example).  I added some clarification on that, as consistency leads to a better ordering of the scripts in the UI.
> Added clarification on how to name SQL scripts.

- docs/architecture/adr/0015-short-lived-browser-services.md
ADR describing response to FireFox `DeadObject` issues due to Observable subscription in the Browser Extension
> ADR on browser short lived services

- docs/getting-started/server/database/ef/index.mdx
Moved the `#Entity Framework` title above the `export` declaration so it would display on the menu.
**Before**
**After**
> Moved title above JSON declaration so that it would display.

- docs/getting-started/server/guide.mdx
BW Server project would not compile using Visual Studio 2019 due to NET 6.0 SDK restrictions. Suggested by Thomas Rittsen @eliykat via gitter.im BW Lobby.
Contributor documentation edits for BitWarden Server Setup guide.
> [PS-2311] Added notes about Visual Studio 2022 requirement for Windows developers.

- docs/contributing/commit-signing.mdx
- docs/getting-started/tools/index.md
We are no longer requiring commit signing, so we should remove these requirements from our documentation.
I thought about leaving them there for informational purposes, but it's not serving much use and it's just more documentation to maintain.
> Remove commit signing requirements

- docs/architecture/autofill/shadow-dom.md
Expand on the autofill documentation that @trmartin4 recently wrote to explain how we handle shadow roots, per the recently merged PR here: https://github.com/bitwarden/clients/pull/4119.
This is branched from the `add-autofill-docs` branch but will automatically retarget `master` when that is merged.
> Add autofill shadowRoot documentation

- docs/getting-started/server/troubleshooting.md
The AppleCrypto error described in our troubleshooting section of the server seems to be pretty common. There have been other fixes found unrelated to the original fix, so we should include those preliminary steps before moving on to the more involved fix.
> Add more troubleshooting to AppleCrypto error

- docs/getting-started/server/sso/okta.mdx
Okta has updated the UI around adding users, so I made some updates to the setup to reflect the new flow.
The UI also does not display the `Authority` to the user (the only proximal value is the `Issuer` which is slightly different).  I changed the documentation to explicitly state the authority to be our Okta instance, as that should change very rarely.
> Sso doc changes

- docs/contributing/code-style/index.md
We have decided to ban the use of code regions within our codebase. This rule mostly applies to C#'s `#regions`, but there are also less standardized regions in TS/JS that we should avoid using as well.
> ban regions in code style

- docs/contributing/code-style/sql.md
We recently discussed in `#code` that we should use `DROP IF EXISTS` to delete tables/views/sprocs. This PR adds this guidance to the T-SQL code style.
There is a bit of duplication in this change, but it matches the layout of the document which is arranged by the thing being modified, not the type of operation.
I've also restructured headings slightly to make them more consistent.
> Add Delete guidance to T-SQL code style

- docs/getting-started/server/guide.md
Moving an errant `.` out of the link:
> Fix broken link typo

- docs/getting-started/clients/browser/biometric.mdx
- docs/getting-started/clients/browser/index.md
It appears Safari currently uses "Settings" terminology to refer to the documented menu options.
> Update Safari Preferences to Settings

- .github/renovate.json
Still pin dependencies but avoid peers e.g. the Node engine.
> Pin except engines and peers

- docs/contributing/featureflags.md
Added section to clarify that a feature flag is required to be defined on the server before use.
> Clarified feature flagging server constant definition

- .github/renovate.json
Per https://github.com/renovatebot/renovate/discussions/16419 and some other info, the prior approach needs additional qualification to split rollup PRs by manager.
> Explicitly match managers

- docs/contributing/featureflags.md
Added a few clarifications to the feature flag doc:
- Added clarification on naming
- Added guidance on when to request flags in LaunchDarkly
- Removed the "technical debt" term from the cleanup tasks to emphasize how this should be a part of the feature and not something that we might get to eventually.
> Clarifications to feature flag doc

- docs/contributing/featureflags.md
Added environment change to what triggers flags to be re-fetched.
Changing the environment changes the API endpoint, which could theoretically change the LD environment (and thus the flag values).
> Added environment change to the feature flag triggers

- docs/getting-started/clients/desktop/native-messaging-test-runner.md
Updated link to desktop client docs that still referenced our old documentation URL.
> Updated broken link to desktop client docs

- docs/contributing/featureflags.md
Describes usage of application settings for feature flag configuration via what was added in https://github.com/bitwarden/server/pull/2963.
> Feature flag configuration via application settings

- docs/architecture/deep-dives/captchas/index.md
The token endpoint for our IdentityServer instance is `/connect/token` not `/token`. The Captcha documentation was incorrect.
> Fixed identity URL path

- docs/getting-started/server/guide.md
Adds instructions for the newly-added `create_linux_certificate.sh` script from #https://github.com/bitwarden/server/pull/2941
> add Linux cert script steps

- docs/getting-started/server/portal.md
The term "Bitwarden Portal" only refers to the cloud-hosted portal that we use internally at Bitwarden to administer the cloud-hosted instance.  For self-hosted customers, the same app is referred to as the "System Management Portal" in our customer-facing documentation and help system.
I've changed the menu option to "System Management Portal" and also added a Bitwarden-specific note about the different naming.
Unrelated, I moved the `Setup` section ahead of the `Configuring Access` section because it flows more with how a user would approach the application.
> Portal naming changes

- docs/contributing/user-secrets.md
- docs/getting-started/clients/web-vault/webauthn.mdx
- docs/getting-started/enterprise/key-connector.mdx
- docs/getting-started/server/advanced-setup.md
- docs/getting-started/server/database/_category_.yml
- docs/getting-started/server/database/ef/index.mdx
- docs/getting-started/server/events.md
- docs/getting-started/server/portal.md
- docs/getting-started/server/scim.md
- docs/getting-started/server/secrets/_category_.yml
- docs/getting-started/server/secrets/index.md
- docs/getting-started/server/self-hosted/_category_.yml
- docs/getting-started/server/self-hosted/index.md
- docs/getting-started/server/sso/_category_.yml
- docs/getting-started/server/troubleshooting.md
- docs/getting-started/server/tunnel.md
- Added documentation to the Advanced Server Setup for how to set up YubiKey 2FA in local development.  This came up on the Auth team with some recent tickets and I had to look in Slack history for recommendations.
- Added `sidebar_position` tags to all of the menu items for the Server setup so that they are alphabetized by title (after the setup guide, which is first)
- Moved User Secrets Reference from Getting Started to Contributing, as this felt like documentation that would be used while developing the code ("contributing") instead of initial setup where we have the helper script defined.
> Add Yubikey 2FA docs and other server-side docs cleanup

- custom-words.txt
- docs/architecture/adr/0021-standard-output-logging.md
Adds "Serilog" to custom words as lint failed once an ADR referring to it was merged. Also fixes a typo in the ADR.
> Add custom word, fix typo

- docs/getting-started/server/guide.md
- docs/getting-started/server/self-hosted/index.md
While going through the onboarding, I had to reset my user secret several times. To do so, I was trying to use the `-clear` parameter as specified in the docs: `pwsh setup_secrets.ps1 -clear:$True`
However, I noticed [that this part of the script](https://github.com/bitwarden/server/blob/master/dev/setup_secrets.ps1#L15) was never being hit.
I changed `$True` to `true` and it started to work:
> setup_secrets: Pass `-clear` as switch

- docs/getting-started/server/self-hosted/index.md
The documentation for selecting the self-hosting profile incorrectly used an em dash (`—`) where it should have used a normal dash (`-`). This caused the dotnet runtime to select the wrong port when running instructions listed in the contributor docs. This commit replaces the em dash with a normal dash.
> use dash when running self-hosted dotnet profile

- docs/contributing/code-style/csharp.md
Fixes typo and makes point clearer in contributing > code-style > csharp.md.
> [PM-3535] Fixed typo in csharp.md

- README.md
This patch adds the missing `run` command (`npm run build`) to the Build step on the README.
Copying the command as is, results in the following error:
```
Unknown command: "build"                          
Did you mean this?                                
npm run build # run the "build" package script
To see a list of supported npm commands, run:
npm help                                   
Process finished with exit code 1
```
> [PM-4161] Fix build command on README.md

- docs/getting-started/clients/index.md
Update clients setup instructions
Add the current directory command to the "Install the dependencies" setup instructions step.
This would make it so all necessary commands are included in the doc. And, by adding it into an existing step, brevity is maintained.
> [PM-4407] docs: add cd command to setup instructions

- package.json
Remove the react overrides for `docusaurus-lunr-search` since they are no longer required with the latest version which was bumped in #231
> Remove `docusaurus-lunr-search` overrides

- docs/contributing/dependencies/index.md
Include how renovate is configured.
> Add documentation on how renovate config is maintained

- docs/getting-started/clients/mobile/android/index.md
- docs/getting-started/clients/mobile/ios/index.mdx
Update mobile requirements given that we need .NET 7.0.x SDK and Android 33 / Xcode 15.
> Update mobile requirements

- docs/getting-started/server/guide.md
- docs/getting-started/server/sso/local.md
Remove the section that is no longer needed after bitwarden/server#3504 merged. This adds a new, optional, step to the local SAML SSO docs for using the certificate we used to require to optionally sign SSO requests.
> Remove Generate Certificates Section

- docs/architecture/index.md
Fixed obsolete link to IcePanel diagram.
Due to the way that shared links are generated in IcePanel, generating a static link would invalidate the dynamic link.  I opted to remove the static link reference and just use the dynamic one instead.
> Fixed IcePanel link

- custom-words.txt
While merging in the updates to the autofill documentation, I neglected to alphabetize the added custom words created for the document. This PR addresses that.
> Alphabetizing the custom-words.txt file

- docs/architecture/deep-dives/captchas/index.md
When we added additional registration recency checks in https://bitwarden.atlassian.net/browse/PM-2471, I added an additional criteria to the Captcha logic (in #211).
It came to my attention that that description could be further clarified to express the intent of the check.
> Clarified logic for captcha.

- docs/architecture/deep-dives/state/derived-state.md
- docs/architecture/deep-dives/state/index.md
Adding documentation for derived state to the state provider deep dive.
I moved this to a separate file because it felt optional and different enough to warrant some extra separation.
> First pass at derived state documentation

- docs/getting-started/server/sso/local.md
With https://github.com/bitwarden/clients/pull/7117, we added an SSO configuration option (defaulting to enabled) that  creates a specific Entity ID in the URL.
In the setup documentation, the URL didn't reflect that change.  Despite the instructions to copy from the values in the web client, the presence of the "copy" UI made it very easy to copy the incorrect URL and set the environment variable incorrectly.
Instead of adding "{yourOrgIdHere}" as was already in the ACS URL, I opted to completely remove any reference to the URLs themselves in the script, so that users will use the values in the UI.  This will prevent us from having to keep the documentation in sync with any future URL structure changes.
> Clarify instructions for local SAML SSO

- docs/architecture/deep-dives/state/index.md
Added additional documentation for new constructor parameter as well as a mapping table to help with migration.
📓 Note the destination of this PR is @justindbaur's larger body of work updating the state provider framework.  I wanted to make sure I had a review before it made it into this larger set of changes, hence the separate PR.
> Added optional constructor parameter and updated mapping instructions.

- README.md
- docs/contributing/accessibility/accessibility.mdx
- docs/contributing/database-migrations/edd.mdx
- docs/contributing/pull-requests/code-review.md
- docs/contributing/pull-requests/index.md
- docs/getting-started/clients/browser/index.md
- docs/getting-started/clients/mobile/android/index.md
- docs/getting-started/clients/mobile/index.md
- docs/getting-started/clients/web-vault/index.mdx
- docs/getting-started/enterprise/directory-connector/index.mdx
- docs/getting-started/enterprise/key-connector.mdx
- docs/getting-started/server/guide.md
- docs/getting-started/server/portal.md
- docs/index.mdx
- src/theme/MDXComponents.tsx
In mixed content formats (like msx), lowercase tags will typically be interpreted as literal HTML (valid or not), even if there is an available React Component defined with lower casing. This was causing the custom `<bitwarden>` and `<community>` tags to render literally instead of using react to conditionally render the wrapped children.
This causes the Bitwarden/Community developer filter to not work, rendering all content in either tag, regardless of the state returned by the `useDevMode` hook.
Uppercasing the jsx tags and references in `src/theme/MDXComponents.tsx` resolves the issue
> [PM-6143] Fix custom bitwarden and community components

- docs/getting-started/server/guide.md
When BitWarden Developers are installing Licensing for local & self hosted instances, Mac Keychain allows the license and key to be installed under different groups and defaults to "Local Items". The current guide does not make it immediately obvious that they must be stored under "Default Keychains > login" in order for it to be recognized during "Build and Run the Server" steps.
This change adds a note in step "Install Licensing Certificate" that explicitly states where the licensing files should be saved.
> Clarify where BitWarden License is installed in Mac Keychain

- docs/getting-started/clients/browser/biometric.mdx
- docs/getting-started/clients/browser/index.md
- docs/getting-started/clients/mobile/ios/index.mdx
- docs/getting-started/clients/mobile/watchos/index.mdx
- docs/getting-started/enterprise/key-connector.mdx
- docs/getting-started/server/guide.md
- docs/getting-started/server/troubleshooting.md
- docs/getting-started/tools/index.md
Throughout the documentation, we were sometimes referring to the Mac operating system as "MacOS" and "macOS". The recommendation in the [Apple Style Guide](https://support.apple.com/en-my/guide/applestyleguide/apsg72b28652/1.0/web/1.0#apd246e83209) is "macOS", and while that document is intended primarily for Apple communications, it seems reasonable for us to match their branding.
This change updates this accordingly.
> Consistently use capitalization of 'macOS' in documentation

- docs/getting-started/server/database/ef/index.mdx
When I was trying to get my local Bitwarden server working with an EF database, I ran into the problem that changing the `secrets.json` file alone was insufficient. After a bit of time, I figured out that calling the `setup_secrets` script again fixed the issue.
It therefore seems reasonable to me to include a note here to remind people to run that script if modifying properties to run the server with an EF.
- It is possible that this is not actually necessary, and there is some other better solution, in which case the docs should be updated to that effect
- I only used `pwsh setup_secrets.ps1 -clear`, and that worked; it's possible the `-clear` flag is unnecessary, though it seems reasonable especially if the `databaseProvider` property might be removed (to return to MSSQL)
> Clarify that changing secrets.json requires reloading the secrets

- docs/architecture/adr/0001-reactive-forms.md
- docs/architecture/adr/0002-public-module-npm-packages.md
- docs/architecture/adr/0003-observable-data-services.md
- docs/architecture/adr/0004-refactor-state-service.md
- docs/architecture/adr/0005-refactor-api-service.md
- docs/architecture/adr/0006-clients-use-jest-mocks.md
- docs/architecture/adr/0007-manifest-v3-browser-memory-caching.md
- docs/architecture/adr/0008-server-CQRS-pattern.md
- docs/architecture/adr/0009-angular-composition-over-inheritance.md
- docs/architecture/adr/0010-angular-ngmodules.md
- docs/architecture/adr/0011-angular-folder-structure.md
- docs/architecture/adr/0012-angular-filename-convention.md
- docs/architecture/adr/0013-deprecate-global-request-response-models.md
- docs/architecture/adr/0014-typescript-strict.md
- docs/architecture/adr/0015-short-lived-browser-services.md
- docs/architecture/adr/0016-decryption-in-views.md
- docs/architecture/adr/0017-watchOS-use-swift.md
- docs/architecture/adr/0018-feature-management.md
- docs/architecture/adr/0019-adopt-web-push.md
- docs/architecture/adr/0020-observability-with-opentelemetry.md
- docs/architecture/adr/0021-standard-output-logging.md
- docs/architecture/adr/index.mdx
- src/components/AdrTable.tsx
Uses new statuses for ADRs. After some review of what others do with them and how we have a number ourselves that we consider ratified but not necessarily appropriate to declare "done", it's better to represent acceptance and future state.
> New ADR statuses

- docs/contributing/code-style/angular.md
Now that we're using Angular 16 we can switch to using the `takeUntilDestoryed` helper which removes the need for a separate observable.
> Replace takeUntil with takeUntilDestroyed

- docs/getting-started/server/events.md
- docs/getting-started/server/self-hosted/index.mdx
Simplify the self-host instructions by removing the recommendation for a separate repository. Reasons:
* it's unnecessary! You can do it all from the same repo
* it's extra effort because you have to clone your repo, copy across your .env and secrets.json files, and then keep your code in sync
* risk of changes getting out of sync between repos, or your user secrets overwriting eachother
I also made some minor layout improvements, e.g. moving information to callouts or tab groups.
I was going to add a section suggesting that you can just run the web client in self-hosted mode (against your cloud server) if you just want to check simple UI functionality. However, you then have to override your web client ports, and it is a bit of a hack which is hard to provide good guidance around. It's …
> Improvements to self-host instructions

- docs/getting-started/mobile/android/index.md
I wanted to change the Android docs to accommodate new macOS/mac developers by including a link to Visual Studio 2022 and changing terms to include newer Apple Silicon chips (M2, M3, etc.).
> [PM-7451] Added link to Visual Studio 2022 and changed M1 to ARM64

- docs/getting-started/server/guide.md
You need the secrets before you run any database migrator by changing the order of the steps.
The _Create database_ step describes a step to run `migrate.ps1` command, which in essence runs two commands for MSSQL server:
1. Get the connectionString by running `$(dotnet user-secrets list --json --project ../src/Api | ConvertFrom-Json).'globalSettings:sqlServer:connectionString'`
2. Run the database migrator with the extracted connection string `dotnet run --project ../util/MsSqlMigratorUtility/ "$msSqlConnectionString"`
With the current documentation, a fresh setup would not contain any secrets, since the `secrets.json` file has not been created yet, resulting in some weird connection error, that does not suggest on the actual problem (lack of validation for expected argument being empty …
> [PM-7738] Configure secrets before creating database

- docs/getting-started/clients/browser/index.md
Add note about manifest v3 being the default for build and build:watch commands
https://github.com/bitwarden/clients/pull/9160 (Do not merge until this PR in `clients` is merged)
> [PM-8101] Add note about manifest v3 being the default for build and build:watch commands

- docs/getting-started/sdk/secrets-manager/integrations/kubernetes.mdx
We are changing how the Secrets Manager SDK gets pulled into sm-kubernetes.  This change should not be committed until after that change is made.
> Removing references to the SDK binaries

- .env.example
- .gitignore
- README.md
- package.json
- scripts/docusaurus-start.sh
- scripts/generate-certs.sh
Allows devs to quickly/easily generate and provide SSL certs to run `contributing-docs` locally without their https-enforcing browsers getting in the way.
> Run docusaurus locally with SSL if certs are provided

- .github/renovate.json
I'd like [renovate to bump the node version in .nvmrc files](https://docs.renovatebot.com/modules/manager/nvm/) when it bumps it everywhere else.
-   👍 (`:+1:`) or similar for great changes
-   📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
-   ❓ (`:question:`) for questions
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
-   🎨 (`:art:`) for suggestions / improvements
-   ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
-   🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
-   ⛏ (`:pick:`) for minor or nitpick changes
> [deps] Have renovate also manage .nvmrc

- docs/contributing/dependencies/index.md
Addressing typo in PR https://github.com/bitwarden/contributing-docs/pull/387.
Fixed typo in earlier PR that removed the end of the sentence.
team …
> Added the intended end of the sentence in the PR update section

- docs/contributing/feature-flags.md
Feedback from team members on lack of understanding of feature flag ownership between environments
As we become more mature in our flag usage and have a USDEV environment, I felt it would be helpful to clarify what the expectations are for flag usage in each environment.
team
- 📝 (`:memo:`) or ℹ️ …
> Added section on ownership of flags in environments

- docs/getting-started/server/guide.md
N/A
Move from Azure SQL Edge to Microsoft SQL Server.
This is due to ARM platform problems on M1 macs for Azure SQL Edge. The database keeps crashing without any reason.
team …
> Move from Azure SQL Edge to native SQL Server

- docs/architecture/deep-dives/authorization.md
N/A
Some follow-up changes to the authorization deep dive based on some recent discussions and experience.
The **main change** is to state that `AuthorizationService` should be called from the controller, rather than in the core layer (the query/command class). There are several reasons for this:
1. I still think that authz is fundamentally an api layer concern, mixing it in with business logic in the core layer makes everything more complex. It's useful to think of these separately.
2. Putting it in the command/query limits their re-use. Some queries may be used internally to check state, and are not returned out to the user. Some commands are used as side-effects with fixed argument values that need to be executed for all users, or may be executed by a job that is not tied to a user. …
> Authorization deep dive amendments

- docs/getting-started/server/advanced-setup.md
- docs/getting-started/server/guide.md
https://bitwarden.atlassian.net/browse/PM-6950
Adds documentation on how to set up GitHub Packages to enable restores of our new NuGet offerings there.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …
> Add server setup for GitHub Packages

- docs/getting-started/sdk/index.md
This was incorrectly set to `languages/sdk-internal` instead of `languages/js/sdk-internal`
You can check the correct path in the SDK repo: https://github.com/bitwarden/sdk/tree/main/languages/js/sdk-internal
team
- ❓ (`:question:`) for …
> Update path to sdk-internal

- .github/labeler.yml
- .github/workflows/labeler.yml
We would like better visibility internally to opened ADRs, so that team members can offer feedback through the Github PR, without tagging the entire engineering organization as reviewers.
To distinguish these ADRs from other updates to the repo, this change will add a `adr` label to the PR when there are changes in the `/docs/architecture/adr` directory.
This label will then be used in upstream automations to trigger notifications.
- Updated any …
> Create labeler for ADR updates

- docs/getting-started/sdk/index.md
- docs/getting-started/sdk/internal/index.md
- docs/getting-started/sdk/secrets-manager/index.mdx
Update docs after the move to SDK internal.
team
- 🎨 …
> Update SDK docs after move to sdk-internal

- docs/contributing/pull-requests/community-pr-process.md
- docs/contributing/pull-requests/index.md
N/A
Provide clarity for our community contributors around what our internal processes are for managing contributions. This is intended to be high-level enough that it doesn't have to change based on individual teams' implementation details around how they manage community PRs, but instead give contributors insight into what the communication points are likely to be when they submit a PR and help them understand why some PRs might take longer than others.
Once deployed, I intend to change the auto-generated message on all community PRs to include a link to this page,.
- Used …
> Add community PR process documentation

- docs/getting-started/clients/browser/biometric.mdx
https://bitwarden.atlassian.net/browse/PM-14402
With the recent IPC changes and developer experience improvements around biometrics, the documentation should be updated to match.
- The IPC proxy is not baked in the application anymore, but is a separate binary that is included with the application.
- MacOS in dev mode can use IPC without requiring an App Store build or disabling Gatekeeper now, so I've removed the warning.
- The desktop app can autodetect the installed developer-mode browser extensions and add them to the manifests. Rewrote the instructions around that part and moved the `Build the Desktop app` section before the `Add the Extension ID for Native Messaging` section, which now should only be done manually as a last resort if the autodetection doesn't work. 
- Contributor …
> Update docs about desktop-browser integration

- docs/getting-started/clients/browser/index.md
PM-15395
The contributing docs use outdated node commands to run builds for non-Chrome browsers
> [PM-15395] Update node commands for building non-chrome browser extensions

- docs/getting-started/server/advanced-setup.md
https://bitwarden.atlassian.net/browse/PM-15201
Adding some more information to make it more explicit on how to find the email content locally.
team …
> [PM-15201] Add info to clarify where to find email contents

- docs/architecture/mobile-clients/android/index.md
- docs/architecture/mobile-clients/ios/index.md
- docs/architecture/sdk/index.md
- docs/architecture/sdk/versioning.md
- docs/getting-started/sdk/secrets-manager/index.mdx
- docs/getting-started/sdk/secrets-manager/integrations/kubernetes.mdx
[bitwarden.atlassian.net/browse/PM-13377](https://bitwarden.atlassian.net/browse/PM-13377)
We're renaming the sdk repository to sdk-sm. Updates the documentation links.
team …
> [PM-13377] Update links to sm sdk

- docs/contributing/commit-signing.mdx
N/A
Now that GitHub's SSH key signing support has matured, recommend using an SSH key for commit verification.
> replace GPG signing recommendation with SSH

- docs/contributing/code-style/rust.md
Write some code style guidelines for writing rust.
team
- 🎨 …
> Provide some code style for rust

- docs/contributing/testing/database/index.md
- docs/getting-started/server/database/ef/index.mdx
https://bitwarden.atlassian.net/browse/PM-10863
This commit adds up to date documentation for running entity framework integration tests for `server`. It has a companion PR for adding some of the mentioned functionality in https://github.com/bitwarden/server/pull/4912
team
- 📝 (`:memo:`) or ℹ️ …
> [PM-14818] Adjust instructions for running EF integration tests

- docs/getting-started/server/events.md
[PM-17562](https://bitwarden.atlassian.net/browse/PM-17562)
Corresponding server PR: https://github.com/bitwarden/server/pull/5323
The above PR adds support for an initial POC of a new feature in the Events pipeline. This PR adds some documentation about how to opt-in and setup those distributed events locally.
team
- 👍 (`:+1:`) or similar for great …
> [PM-17562] Add documentation for the initial Distributed Events POC

- docs/contributing/commit-signing.mdx
N/A
Onboarding Feedback:
Not clear when `git config <name>=<value>` syntax would have been valid (a cursory look back to the earliest available official [`git config` docs](https://git-scm.com/docs/git-config/2.0.5) don't show it, but I may have missed something). 
`<name>=<value>` is valid syntax inside of a .gitconfig file however, but not in this command. 
As of 2.46.0, git config supports subcommands (i.e. `git config set --global <name> <value>`.
As of this writing, newly provisioned macbooks ship with git version 2.39.5 (Apple Git-154).
As an illustration, this supports neither the most recent subcommand syntax, nor the current documentation syntax:
```
git version 2.39.5 (Apple Git-154)
user@macbook % git config set butter.bread true
error: key does not contain a section: set …
```
> Use maximum compatible `git config` syntax.

- docs/getting-started/tools/index.md
This may be more of a conversation prompt (I can demote back to draft PR), but following [the link](https://visualstudio.microsoft.com/vs/mac/) currently in the docs here indicates that Visual Studio for Mac is at EOL, and is no longer being supported and maintained as of August 2024, and therefore only downloadable to those with a pre-existing license.
I don't have C# IDE expertise but thought we could come up with an alternative experience here for new contributors. 
- Communicated to DevOps any …
> Remove link indicating EOL for Visual Studio for Mac

- docs/getting-started/business/splunk-app.md
N/A
Adds a warning about Splunk v9.4 being incompatible with Apple Silicon. The root cause is dependent on the user’s cpu architecture (and their support for the AVX instruction set) for the new mongoDB 7.1 dependency in Splunk v9.4. ARM based processors (like Apple silicon) don’t support AVX and therefore, the KVstore (mongoDB) fails to initialize. This can be seen in the container’s shell by running ./splunk show kvstore-status and the resultant status being in a failed state before we ever run the deploy script. This was further confirmed by running the v9.4 container on a Linux x86 based system, which saw the KVStore initialize without issue.
- Written new unit and / or integration tests where …
> add warning about splunk incompatabilty with v9.4 for apple silicon

- docs/contributing/code-style/angular.md
There has previously been some confusion for import statements. It would be helpful to have recommendations in the style guide. Open to any recommendations or suggestions.
team …
> Add code style guide for Angular & TypeScript import statements

- docs/getting-started/sdk/internal/index.md
Our `sdk-internal` instructions ask engineers to look at the relevant crate `README` but did not link to those files.  This PR adds links for easy reference.  These felt stable enough to include as links as they should not change frequently.
team
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …
> Added links to SDK crate README pages

- docs/contributing/dependencies/index.md
- docs/contributing/template-repository.md
Update the Dependency Management section to include the documentation on dependency management strategies that was previously documented internally.
I incorporated the documentation from the Template Repository section, as it offered a excellent summary of our default Renovate configuration, and linked to it from the Template Repository page.
I also removed the explicit references to the teams that owned Key Connector and Directory Connector, so that we don't have to keep them up to date if the teams change (as Auth already had).
- Used internationalization (i18n) for all UI …
> Incorporate dependency management strategies

- docs/contributing/dependencies/index.md
In #583 I added additional documentation on our dependency management process.  I neglected to add anything describing our `minimumReleaseAge` policy, which is an important part of the trust we put in the dependency updates that we review.
team
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …
> Add documentation of minimum release age in our Renovate config

- docs/getting-started/server/database/ef/index.mdx
N/A
@justindbaur pointed out that there's a `.env` file, so I've adjusted the instructions to include a step confirming the environment variables match.
This PR also moves the application config above the database config so that a reader encounters `secrets.json` before it's referenced by the database config section's tips.
([rendered](https://add-dot-env-reminder.contributing-docs.pages.dev/getting-started/server/database/ef/))
- ❌ (`:x:`) or ⚠️ …
> confirm passwords match between .env and secrets.json

- .github/workflows/build.yml
- .github/workflows/lint.yml
[PM-22030](https://bitwarden.atlassian.net/browse/PM-22030)
The `contributing-docs` build checks will begin failing as of the [latest version bump to cspell](https://github.com/bitwarden/contributing-docs/pull/598), owning to the workflow using node v18 instead of the project-defined version (v22).
Consequently, the `npm run spellcheck` script works locally with the correct node version running, but fails in the action runners.
- ❌ (`:x:`) or ⚠️ …
> [PM-22132] Bugfix - Have workflows use the version of node specified in the project files

- docs/architecture/adr/0026-dotnet-dependency-injection-enhancements.md
- docs/contributing/code-style/csharp.md
N/A
Add ADR for encouraging use of `TryAdd` overloads in .NET dependency injection.
team
issue and could …
> Propose ADR for using `TryAdd` in .NET dependency injection

- docs/contributing/code-style/enums.md
N/A
Fix missing `typeof` in enum-like code samples.
[Rendered](https://fix-missing-typeof.contributing-docs.pages.dev/contributing/code-style/enums)
> fix missing typeof

- custom-words.txt
- docs/getting-started/mobile/ios/index.md
Update iOS Getting started guide to note up to date Xcode and simulator version to use.
team
issue and could …
> Update iOS Getting Started guide

- docs/architecture/deep-dives/ipc.md
Add high level documentation of the IPC framework
team
- 🎨 …
> Add IPC deep dive

- docs/getting-started/server/self-hosted/index.mdx
To make it clear that the sqlcmd command referenced, should be run from the context of the mssql container.
There otherwise currently isn't any indication on where to run that command from such that it has the desired effect.
team
- ❓ …
> Self-hosted guide clarify context to run sqlcmd from

- docs/contributing/code-style/sql.md
https://bitwarden.atlassian.net/browse/DBOPS-3
The goal for this PR is to clearly define the coding style, naming conventions, etc. for SQL code. This PR takes the existing doc and combines it with with a document generated by AI using on the existing SQL files in the code base as a baseline. 
team
- 📝 (`:memo:`) …
> [DBOPS-3] Updated SQL code style to match our current codebase

- docs/contributing/index.md
Improve the contributing guide to emphasize engaging in GH discussions for changes due to new features or significant bug fixes before opening PRs.
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
> Improve emphasis on engaging in discussion before significant PRs

- docs/getting-started/clients/browser/biometric.mdx
- docs/getting-started/clients/browser/index.md
Simplify safari instructions
team
- 🎨 (`:art:`) for …
> Safari now supports unpacked temporary extension - no need to run it through xcode

- docs/getting-started/clients/desktop/mac/index.md
- renames the current "Testing" section to "Build", which is more accurate
- adds a new testing section that describes the how to do verification of builds
team
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …
> Add section about testing desktop mac store builds

- docs/contributing/dependencies/index.md
N/A
Add a note advising readers of the upcoming rename to the Renovate bot, making it easier to arrive at documentation when searching "mend", "mend bot", or "mend [bot]". The official announcement has also been included in part and linked to.
team
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …
> (dependencies) Add note for upcoming rename of Renovate bot to Mend bot.
